name: covoiturage_benin_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  file_selector: ^1.0.3
  dio: ^5.8.0
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  logger: ^2.7.0
  image_picker: ^1.1.2
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.11.0
  image: ^4.1.7
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/operators/
