class BeninLocations {
  BeninLocations._();

  /// 77 communes du Bénin, triées alphabétiquement.
  static const List<String> cities = [
    'Abomey',
    'Abomey-Calavi',
    'Adja-Ouèrè',
    'Adjarra',
    'Adjohoun',
    'Agbangnizoun',
    'Aguègues',
    'Akpro-Missérété',
    'Allada',
    'Aplahoué',
    'Athiémé',
    'Avrankou',
    'Banikoara',
    'Bantè',
    'Bassila',
    'Bembèrèkè',
    'Bohicon',
    'Bonou',
    'Bopa',
    'Boukoumbé',
    'Cobly',
    'Comè',
    'Copargo',
    'Cotonou',
    'Covè',
    'Dangbo',
    'Dassa-Zoumé',
    'Djakotomè',
    'Djidja',
    'Djougou',
    'Dogbo',
    'Glazoué',
    'Gogounou',
    'Grand-Popo',
    'Houeyogbé',
    'Ifangni',
    'Kalalé',
    'Kandi',
    'Karimama',
    'Kérou',
    'Kétou',
    'Klouékanmè',
    'Kouandé',
    'Kpomassè',
    'Lalo',
    'Lokossa',
    'Malanville',
    'Materi',
    'Natitingou',
    "N'Dali",
    'Nikki',
    'Ouaké',
    'Ouèssè',
    'Ouidah',
    'Ouinhi',
    'Parakou',
    'Péhunco',
    'Pèrèrè',
    'Pobè',
    'Porto-Novo',
    'Sakété',
    'Savalou',
    'Savè',
    'Ségbana',
    'Sèmè-Kpodji',
    'Sinendé',
    'So-Ava',
    'Tanguiéta',
    'Tchaourou',
    'Toffo',
    'Tori-Bossito',
    'Toucountouna',
    'Toviklin',
    'Zagnanado',
    'Za-Kpota',
    'Zè',
    'Zogbodomey',
  ];

  static const Map<String, List<String>> _neighborhoods = {
    // ── ALIBORI ───────────────────────────────────────────────────────────────
    'Banikoara': [
      'Angaradébou',
      'Banikoara',
      'Béssassi',
      'Bindèkou',
      'Boudougoubi',
      'Daïbérou',
      'Dèmba-Pérou',
      'Founougo',
      'Gah',
      'Gnandarou',
      'Gomparou',
      'Goumori',
      'Goungoun',
      'Kokey',
      'Kokiborou',
      'Kolibérou',
      'Kobirou',
      'Ounet',
      'Pèrèrè-Boko',
      'Sompèrèkou',
      'Soroko',
      'Toura',
    ],
    'Gogounou': [
      'Bagou',
      'Banamarou',
      'Béro',
      'Bindèkou',
      'Boukoubrou',
      'Garou',
      'Gogounou',
      'Gounarou',
      'Kalmama',
      'Laminou',
      'Ouara',
      'Sori',
      'Zoungou-Pantrossi',
    ],
    'Kandi': [
      'Albarika',
      'Angaradébou',
      'Bensèkou',
      'Donwari',
      'Gnangourou',
      'Kandi I',
      'Kandi II',
      'Kandi III',
      'Kassakou',
      'Kodowari',
      'Kourtéré',
      'Saah',
      'Sam',
      'Sonsoro',
      'Taïarou',
    ],
    'Karimama': [
      'Birni-Lafia',
      'Bogo-Bogo',
      'Fété',
      'Karimama',
      'Kompa',
      'Monsey',
      'Sokarou',
    ],
    'Malanville': [
      'Garou',
      'Guènè',
      'Kassa',
      'Madécali',
      'Malanville',
      'Sorbon',
      'Tomboutou',
    ],
    'Ségbana': [
      'Basso',
      'Gah',
      'Libanté',
      'Liboussou',
      'Lougou',
      'Ségbana',
      'Sokotindji',
    ],

    // ── ATACORA ───────────────────────────────────────────────────────────────
    'Boukoumbé': [
      'Boukoumbé',
      'Dipoli',
      'Korontière',
      'Kossoucoingou',
      'Manta',
      'Natta',
      'Tabota',
    ],
    'Cobly': [
      'Cobly',
      'Datori',
      'Kountori',
      'Natèri',
      'Tapoga',
    ],
    'Kérou': [
      'Brignamaro',
      'Firou',
      'Kérou',
      'Koabagou',
      'Kpébiérou',
    ],
    'Kouandé': [
      'Birni',
      'Chabi-Couma',
      'Fo-Tancé',
      'Guilmaro',
      'Kpéré',
      'Kouandé',
      'Oroukayo',
    ],
    'Materi': [
      'Dassari',
      'Gouandé',
      'Kantanguié',
      'Materi',
      'Nodi',
      'Tantèga',
      'Tchianhoun-Cossi',
    ],
    'Natitingou': [
      'Boriyarou',
      'Dèdjannoukon',
      'Foumarou',
      'Kantindi',
      'Kèbèrou',
      'Kotapounga',
      'Kouaba',
      'Kouandata',
      'Natitingou I',
      'Natitingou II',
      'Natitingou III',
      'Natitingou IV',
      'Perma',
      'Piékou',
      'Tchoumi-Tchoumi',
    ],
    'Péhunco': [
      'Gnémasson',
      'Kèrou',
      'Péhunco',
      'Tobré',
    ],
    'Tanguiéta': [
      'Cotiacou',
      "N'Dahonta",
      'Taïakou',
      'Tanongou',
      'Tanguiéta',
    ],
    'Toucountouna': [
      'Kouarfa',
      'Tampègre',
      'Toucountouna',
    ],

    // ── ATLANTIQUE ────────────────────────────────────────────────────────────
    'Abomey-Calavi': [
      'Abomey-Calavi',
      'Agori',
      'Akassato',
      'Calavi-Centre',
      'Dèkanmè',
      'Gbèdagba',
      'Glo-Djigbé',
      'Godomey',
      'Hévié',
      'Houèdo',
      'Kpanroun',
      'Miniffi',
      'Ouèdo',
      'Togba',
      'Womè',
      'Zinvié',
    ],
    'Allada': [
      'Agbanou',
      'Ahouannonzoun',
      'Allada',
      'Attogon',
      'Avakpa',
      'Ayou',
      'Hinvi',
      'Lissègazoun',
      'Lon-Agonmey',
      'Sékou',
      'Togoudo',
      'Tokpa-Avagoudo',
    ],
    'Kpomassè': [
      'Aganmalomè',
      'Agbanto',
      'Agonkanmè',
      'Dèdomè',
      'Dèkanmè',
      'Kpomassè',
      'Sègbèya',
      'Sègbohoué',
      'Tokpa-Domè',
    ],
    'Ouidah': [
      'Avlékété',
      'Dahoué',
      'Djègbadji',
      'Docomey',
      'Gakpé',
      'Houakpè-Daho',
      'Ouidah I',
      'Ouidah II',
      'Ouidah III',
      'Ouidah IV',
      'Ouakpé-Daho',
      'Pahou',
      'Savi',
      'Sogbadji',
      'Tovè',
    ],
    'So-Ava': [
      'Ahomey-Lokpo',
      'Dèkanmey',
      'Ganvié I',
      'Ganvié II',
      'Houèdo-Aguèkon',
      'So-Ava',
      'Vèkky',
    ],
    'Toffo': [
      'Aguè',
      'Colli-Agbamè',
      'Coussi',
      'Damè',
      'Djanglanmè',
      'Houègbo',
      'Kpomè',
      'Sè',
      'Sèhoué',
      'Toffo-Aguè',
    ],
    'Tori-Bossito': [
      'Avamè',
      'Azohoué-Aliho',
      'Azohoué-Cada',
      'Tori-Bossito',
      'Tori-Cada',
      'Tori-Garé',
    ],
    'Zè': [
      'Adjan',
      'Dawè',
      'Djigbé',
      'Dodji-Bata',
      'Hèkanmè',
      'Koundokpoé',
      'Sèdjè-Dènou',
      'Sèdjè-Houègoudo',
      'Tangbo-Djèvié',
      'Yokpo',
      'Zè',
    ],

    // ── BORGOU ────────────────────────────────────────────────────────────────
    'Bembèrèkè': [
      'Bembèrèkè',
      'Bèroubouay',
      'Bouanri',
      'Gamia',
      'Ina',
      'Kalalé-Boko',
    ],
    'Kalalé': [
      'Basso',
      'Bouka',
      'Derassi',
      'Dunkassa',
      'Kalalé',
      'Péonga',
      'Sorèkali',
    ],
    "N'Dali": [
      'Bori',
      'Gbègourou',
      "N'Dali",
      'Ouènou',
      'Sirarou',
    ],
    'Nikki': [
      'Biro',
      'Gnonkourakali',
      'Nikki',
      'Ouènou',
      'Sérèkalé',
      'Suya',
      'Tasso',
    ],
    'Parakou': [
      'Albarika',
      'Banikanni',
      'Boro-Bana',
      'Cica',
      'Doumé',
      'Gah',
      'Guèmè',
      'Hamdallaye',
      'Kpébié',
      'Ladji',
      'Madina',
      'Parakou-Centre',
      'Titirou',
      'Tourou',
      'Wanrou',
      'Zongo',
    ],
    'Pèrèrè': [
      'Gninsy',
      'Guinagourou',
      'Kpanè',
      'Pèbié',
      'Pèrèrè',
      'Sontou',
    ],
    'Sinendé': [
      'Fo-Bouré',
      'Sèrèké',
      'Sikki',
      'Sinendé',
    ],
    'Tchaourou': [
      'Alafiarou',
      'Bétérou',
      'Goro',
      'Kika',
      'Sanson',
      'Tchatchou',
      'Tchaourou',
    ],

    // ── COLLINES ──────────────────────────────────────────────────────────────
    'Bantè': [
      'Agoua',
      'Akpassi',
      'Atokoligbé',
      'Bantè',
      'Bobé',
      'Gouka',
      'Koko',
      'Lougba',
      'Pira',
    ],
    'Dassa-Zoumé': [
      'Akofodjoule',
      'Dassa I',
      'Dassa II',
      'Gbaffo',
      'Kèrè',
      'Kpingni',
      'Lèma',
      'Paouingnan',
      'Soclogbo',
      'Trè',
    ],
    'Glazoué': [
      'Aklankpa',
      'Assanté',
      'Glazoué',
      'Gomè',
      'Kpakpaza',
      'Magoumi',
      'Ouèdèmè',
      'Sokponta',
      'Thio',
      'Zaffè',
    ],
    'Ouèssè': [
      'Challa-Ogoi',
      'Djègbé',
      'Gbanlin',
      'Kemon',
      'Kilibo',
      'Laminou',
      'Odougba',
      'Ouèssè',
      'Toui',
    ],
    'Savalou': [
      'Djaloukou',
      'Doumè',
      'Gobada',
      'Kpataba',
      'Lahotan',
      'Lèma',
      'Logozohoué',
      'Monkpa',
      'Ottola',
      'Ouèssè',
      'Savalou-Aga',
      'Savalou-Agbado',
      'Savalou-Attaké',
      'Tchetti',
    ],
    'Savè': [
      'Adido',
      'Bèssè',
      'Boni',
      'Kaboua',
      'Offè',
      'Okpara',
      'Plateau',
      'Sakin',
    ],

    // ── COUFFO ────────────────────────────────────────────────────────────────
    'Aplahoué': [
      'Aplahoué',
      'Atomè',
      'Azovè',
      'Dèkpo',
      'Godohou',
      'Kissamey',
      'Lonkly',
    ],
    'Djakotomè': [
      'Adjintimey',
      'Bètoumey',
      'Djakotomey I',
      'Djakotomey II',
      'Gohomey',
      'Houègamey',
      'Kinkinhoué',
      'Kokohoué',
      'Kpoba',
      'Sokouhoué',
    ],
    'Dogbo': [
      'Ayomi',
      'Dèvè',
      'Honton',
      'Lokogohoué',
      'Madjré',
      'Tota',
      'Totchangni',
    ],
    'Klouékanmè': [
      'Adjahonmè',
      'Ahogbèya',
      'Aya-Hohoué',
      'Djotto',
      'Hondji',
      'Klouékanmè',
      'Lanta',
      'Tchikpé',
    ],
    'Lalo': [
      'Adoukandji',
      'Ahodjinnako',
      'Ahomadègbè',
      'Banigbé',
      'Gnizounmè',
      'Hlassamè',
      'Lalo',
      'Lokogba',
      'Tchito',
      'Tohou',
      'Zalli',
    ],
    'Toviklin': [
      'Adjido',
      'Avèdjin',
      'Doko',
      'Houèdogli',
      'Missinko',
      'Tannou-Gola',
      'Toviklin',
    ],

    // ── DONGA ─────────────────────────────────────────────────────────────────
    'Bassila': [
      'Alèdjo',
      'Bassila',
      'Manigri',
      'Pènèssoulou',
    ],
    'Copargo': [
      'Anandana',
      'Copargo',
      'Pabègou',
      'Singrè',
    ],
    'Djougou': [
      'Barei',
      'Barienou',
      'Bellefoungou',
      'Bougou',
      'Djougou I',
      'Djougou II',
      'Djougou III',
      'Kolokondè',
      'Onklou',
      'Patargo',
      'Pèlèbina',
      'Sérou',
    ],
    'Ouaké': [
      'Badjoudé',
      'Kondé',
      'Ouaké',
      'Séméré I',
      'Séméré II',
      'Tchalinga',
    ],

    // ── LITTORAL ──────────────────────────────────────────────────────────────
    'Cotonou': [
      'Agbato',
      'Agla',
      'Agontinkon',
      'Aïbatin',
      'Aïdjèdo',
      'Akpakpa',
      'Akpakpa-Dodomey',
      'Anonvikomè',
      'Avotrou',
      'Cadjèhoun',
      'Cocotiers',
      'Dantokpa',
      'Enagnon',
      'Fifadji',
      'Ganhi',
      'Gbèdjromèdji',
      'Gbégamey',
      'Haie Vive',
      'Houeyiho',
      'Jéricho',
      'Jonquet',
      'Kindonou',
      'Kpankpan',
      'Ladji',
      'Mènontin',
      'Midombo',
      'Missèbo',
      'Sainte Rita',
      'Saint-Michel',
      'Sikècodji',
      'Tokpa',
      'Vèdoko',
      'Wologuèdè',
      'Xwlacodji',
      'Zogbo',
      'Zongo',
    ],

    // ── MONO ──────────────────────────────────────────────────────────────────
    'Athiémé': [
      'Adohoun',
      'Atchannou',
      'Athiémé',
      'Dèdèkpoé',
      'Kpinnou',
    ],
    'Bopa': [
      'Agbodji',
      'Badazoui',
      'Bopa',
      'Gbakpodji',
      'Lobogo',
      'Possotomè',
      'Yègodoé',
    ],
    'Comè': [
      'Agatogbo',
      'Akodéha',
      'Comè',
      'Ouèdèmè-Pèdah',
      'Oumako',
    ],
    'Grand-Popo': [
      'Adjaha',
      'Agoué',
      'Avloh',
      'Djanglanmey',
      'Gbèhoué',
      'Grand-Popo',
      'Sazoué',
    ],
    'Houeyogbé': [
      'Dahè',
      'Doutou',
      'Honhoué',
      'Houeyogbé',
      'Sè',
      'Zoungbonou',
    ],
    'Lokossa': [
      'Agamè',
      'Ahouannonzoun',
      'Houin',
      'Koudo',
      'Lokossa',
      'Ouèdèmè',
      'Tankpè',
    ],

    // ── OUÉMÉ ─────────────────────────────────────────────────────────────────
    'Adjarra': [
      'Adjarra I',
      'Adjarra II',
      'Aglogbé',
      'Honvié',
      'Malanhoui',
      'Mèdèdjonou',
    ],
    'Adjohoun': [
      'Adjohoun',
      'Akpadanou',
      'Awonou',
      'Azowlissè',
      'Dèmè',
      'Gangban',
      'Kodé',
      'Togbota',
    ],
    'Aguègues': [
      'Avagbodji',
      'Houèdomè',
      'Zoungamè',
    ],
    'Akpro-Missérété': [
      'Akpro-Missérété',
      'Gomè-Sota',
      'Katagon',
      'Vakon',
      'Zoungbomè',
    ],
    'Avrankou': [
      'Atchoukpa',
      'Avrankou',
      'Djomon',
      'Gbozounmè',
      'Kouty',
      'Ouanho',
      'Sado',
    ],
    'Bonou': [
      'Affamè',
      'Atchonsa',
      'Bonou',
      'Damè-Wogon',
      'Houinviguè',
    ],
    'Dangbo': [
      'Dangbo',
      'Dèkin',
      'Gbèko',
      'Houèdomey',
      'Hozin',
      'Kessounou',
      'Zoungué',
    ],
    'Porto-Novo': [
      'Agatogbo',
      'Agonkanmè',
      'Avassa',
      'Catchi',
      'Djassin',
      'Djègbé',
      'Docomey',
      'Ganhoua',
      'Gbèdégon',
      'Gbèko',
      'Houinto',
      'Kpankpan',
      'Louho',
      'Mènontin',
      'Ouando',
      'Ségbèya',
      'Togoudo',
      'Tokpanta',
      'Yénawa',
      'Zounguè',
    ],
    'Sèmè-Kpodji': [
      'Agblangandan',
      'Aholouyèmè',
      'Djèrègbé',
      'Ekpè',
      'Sèmè-Kpodji',
      'Tohoué',
    ],

    // ── PLATEAU ───────────────────────────────────────────────────────────────
    'Adja-Ouèrè': [
      'Adja-Ouèrè',
      'Ikpinlè',
      'Kpoulou',
      'Massè',
      'Oko-Akaré',
      'Tatonnoukon',
    ],
    'Ifangni': [
      'Banigbé',
      'Daagbé',
      'Ifangni',
      'Ko-Koumolou',
      'Lagbé',
      'Tchaada',
    ],
    'Kétou': [
      'Adakplamè',
      'Idigny',
      'Kétou',
      'Kpankou',
      'Odometa',
      'Okpometa',
    ],
    'Pobè': [
      'Ahoyèyè',
      'Igana',
      'Issaba',
      'Pobè',
      'Towè',
    ],
    'Sakété': [
      'Aguidi',
      'Ita-Djèbou',
      'Sakété I',
      'Sakété II',
      'Takon',
      'Yoko',
    ],

    // ── ZOU ───────────────────────────────────────────────────────────────────
    'Abomey': [
      'Agbokpa',
      'Ahouanmènou',
      'Détohou',
      'Djèmè',
      'Djègbé',
      'Hountondji',
      'Hounli',
      'Lègbassa',
      'Sèhoun',
      'Sowègan',
      'Vidolé',
      'Zounzonmè',
    ],
    'Agbangnizoun': [
      'Adahondjigon',
      'Adingningon',
      'Agbangnizoun',
      'Kinta',
      'Kpota',
      'Lissazounmè',
      'Sahé',
      'Siwè',
      'Tanvè',
      'Zoungoudo',
    ],
    'Bohicon': [
      'Agongointo',
      'Avogbana',
      'Bohicon I',
      'Bohicon II',
      'Gnidjazoun',
      'Kpèdèkpo',
      'Lissèzoun',
      'Ouassaho',
      'Passagon',
      'Saclo',
      'Sodohomè',
      'Sowègan',
    ],
    'Covè': [
      'Adogbé',
      'Gounli',
      'Houèko',
      'Houèn-Hounsô',
      'Lainta-Cogbé',
      'Naogon',
      'Soli',
      'Zogba',
    ],
    'Djidja': [
      'Agondji',
      'Agouna',
      'Dan',
      'Djidja',
      'Dohouimè',
      'Gobé',
      'Monsourou',
      'Mougnon',
      'Oungbègamè',
      'Outo',
      'Setto',
      'Zoukou',
    ],
    'Ouinhi': [
      'Dasso',
      'Ouinhi',
      'Sagon',
      'Tohoué',
    ],
    'Zagnanado': [
      'Agonli-Houègbo',
      'Baname',
      'Don-Tan',
      'Dovi',
      'Kpèdèkpo',
      'Zagnanado',
    ],
    'Za-Kpota': [
      'Allahè',
      'Assalin',
      'Houngomey',
      'Kpakpamè',
      'Kpozoun',
      'Za-Kpota',
      'Za-Tanta',
      'Zèko',
    ],
    'Zogbodomey': [
      'Akiza',
      'Avlamè',
      'Cana I',
      'Cana II',
      'Domè',
      'Koussoukpa',
      'Kpokissa',
      'Massi',
      'Tanwè-Hessou',
      'Zogbodomey',
      'Zoukou',
    ],
  };

  /// Retourne les quartiers/villages de la commune donnée.
  /// Retourne ["Centre"] si la commune n'a pas de liste détaillée.
  static List<String> neighborhoods(String city) {
    return _neighborhoods[city] ?? ['Centre'];
  }
}
