class BeninLocations {
  BeninLocations._();

  /// Toutes les communes du Bénin, triées alphabétiquement.
  static const List<String> cities = [
    'Abomey',
    'Abomey-Calavi',
    'Adja-Ouèrè',
    'Adjarra',
    'Adjohoun',
    'Agbangnizoun',
    'Aglangandan',
    'Akpro-Missérété',
    'Allada',
    'Aplahoué',
    'Athiémé',
    'Avrankou',
    'Banikoara',
    'Bantè',
    'Bassila',
    'Bembèrèkè',
    'Bohicon',
    'Bonou',
    'Bopa',
    'Boukoumbé',
    'Cobly',
    'Comè',
    'Copargo',
    'Cotonou',
    'Covè',
    'Dangbo',
    'Dassa-Zoumé',
    'Djakotomè',
    'Djidja',
    'Djougou',
    'Dogbo',
    'Glazoué',
    'Gogounou',
    'Grand-Popo',
    'Houeyogbé',
    'Ifangni',
    'Kalalé',
    'Kandi',
    'Karimama',
    'Kérou',
    'Kétou',
    'Klouékanmè',
    'Kouandé',
    'Kpomassè',
    'Lalo',
    'Lokossa',
    'Malanville',
    'Materi',
    'Missérété',
    'Mono',
    'Natitingou',
    'N\'Dali',
    'Nikki',
    'Ouaké',
    'Ouèssè',
    'Ouinhi',
    'Parakou',
    'Péhunco',
    'Pèrèrè',
    'Pobè',
    'Porto-Novo',
    'Sakété',
    'Savalou',
    'Savè',
    'Ségbana',
    'Sèmè-Podji',
    'Sinendé',
    'So-Ava',
    'Tchaourou',
    'Tanguiéta',
    'Toffo',
    'Tori-Bossito',
    'Toviklin',
    'Zagnanado',
    'Za-Kpota',
    'Zè',
    'Zogbodomey',
  ];

  static const Map<String, List<String>> _neighborhoods = {
    'Cotonou': [
      'Agbato',
      'Agla',
      'Aïbatin',
      'Aïdjèdo',
      'Akpakpa',
      'Anonvikomè',
      'Cadjèhoun',
      'Cocotiers',
      'Dantokpa',
      'Enagnon',
      'Fifadji',
      'Ganhi',
      'Gbèdjromèdji',
      'Gbégamey',
      'Godomey',
      'Haie Vive',
      'Houeyiho',
      'Jéricho',
      'Jonquet',
      'Kindonou',
      'Kpankpan',
      'Ladji',
      'Mènontin',
      'Missèbo',
      'Sainte Rita',
      'Saint-Michel',
      'Sikècodji',
      'Tokpa',
      'Vèdoko',
      'Wologuèdè',
      'Xwlacodji',
      'Zogbo',
      'Zongo',
    ],
    'Abomey-Calavi': [
      'Akassato',
      'Calavi-Centre',
      'Gbèdagba',
      'Glo-Djigbé',
      'Godomey',
      'Houeyiho',
      'Ouèdo',
      'Togba',
      'Womè',
      'Zinvié',
    ],
    'Porto-Novo': [
      'Agatogbo',
      'Agonkanmey',
      'Catchi',
      'Djassin',
      'Djégbé',
      'Houinto',
      'Louho',
      'Ouando',
      'Segbeya',
      'Togoudo',
      'Yénawa',
    ],
    'Parakou': [
      'Albarika',
      'Banikanni',
      'Cica',
      'Gah',
      'Guèmè',
      'Kpébié',
      'Ladji',
      'Madina',
      'Titirou',
      'Tourou',
      'Wanrou',
      'Zongo',
    ],
    'Bohicon': [
      'Avogbamè',
      'Kpèdékpo',
      'Lissèzoun',
      'Ouassi',
      'Passagon',
      'Sacré-Cœur',
      'Sodohomè',
    ],
    'Abomey': [
      'Agblomè',
      'Centre',
      'Djèmè',
      'Hountondji',
      'Sèhoué',
      'Vidolé',
    ],
    'Ouidah': [
      'Brazil',
      'Centre',
      'Daho',
      'Kpodji',
      'Pahou',
      'Savi',
      'Sogbadji',
      'Tovè',
    ],
    'Sèmè-Podji': [
      'Agblangandan',
      'Centre',
      'Djèrègbé',
      'Kpoba',
      'Tohoué',
    ],
    'Lokossa': [
      'Agamè',
      'Centre',
      'Houin',
      'Koudo',
    ],
    'Natitingou': [
      'Centre',
      'Gandigate',
      'Kpéwa',
      'Perma',
    ],
    'Djougou': [
      'Barienou',
      'Centre',
      'Kolina',
      'Pélébina',
    ],
    'Kandi': [
      'Centre',
      'Donwari',
      'Kassakou',
      'Saah',
    ],
    'Malanville': [
      'Centre',
      'Garou',
      'Madécali',
    ],
    'Savalou': [
      'Assanta',
      'Centre',
      'Doumè',
      'Gabè',
    ],
    'Allada': [
      'Attogon',
      'Centre',
      'Sékou',
      'Togoudo',
    ],
    'Dassa-Zoumé': [
      'Centre',
      'Kèrè',
      'Paouignan',
    ],
    'Glazoué': [
      'Centre',
      'Magoumi',
    ],
    'Nikki': [
      'Centre',
      'Gbanlin',
    ],
    'Parakou': [
      'Albarika',
      'Banikanni',
      'Cica',
      'Gah',
      'Guèmè',
      'Kpébié',
      'Ladji',
      'Madina',
      'Titirou',
      'Tourou',
      'Wanrou',
      'Zongo',
    ],
    'Pobè': [
      'Centre',
      'Igana',
    ],
    'Kétou': [
      'Centre',
    ],
    'Sakété': [
      'Centre',
      'Dékanmè',
    ],
    'Grand-Popo': [
      'Agoué',
      'Centre',
      'Djanglanmè',
    ],
    'Comè': [
      'Centre',
    ],
    'Aplahoué': [
      'Azovè',
      'Centre',
      'Djakotomè',
    ],
    'Tchaourou': [
      'Bétérou',
      'Centre',
    ],
    'Banikoara': [
      'Centre',
      'Founougo',
    ],
    'Tanguiéta': [
      'Centre',
      'Mékrou',
    ],
    'Savè': [
      'Centre',
      'Kaboua',
      'Okpara',
    ],
  };

  /// Retourne les quartiers de la ville donnée.
  /// Retourne ["Centre"] si la ville n'a pas de liste détaillée.
  static List<String> neighborhoods(String city) {
    return _neighborhoods[city] ?? ['Centre'];
  }
}
